name: Generate Directory Index

on:
  push:
    branches:
      - main

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Index File
        uses: gacts/directory-listing@v1
        with:
          target: .
          
      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add index.html
          git commit -m "Automated update of index.html directory listing" || exit 0
          git push
